### ISSUE TITLE
Suggestion - add parameter fields to prediction zone feature class

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#68]
It would be useful to, in addition to or instead of the CREATEDATE field in the prediction zone feature class have a field that's the Initial Processing Date (the actual date, not just 'today' or 'yesterday' as entered in the tool parameters). Also to have the spatial and temporal influence parameters as fields as well. I'm running a bunch of iterations combining different spatial/temporal influence and initial processing dates and as these accumulate in the prediction zones feature class I want to be able to distinguish between them more easily than just using the created date/time.

What I am manually doing as a very small test of predictive accuracy is generating the zones then looking to see if there are any offences within the zones the day after the initial processing date. If the parameters were in the feature class it would make it easier then (I think, even if beyond my current modelbuilder/python capabilities!) to build and run a process to do this iteratively and automatically (generate zone, look in input file for offences one day after initial processing date, output: how many in and out of zones on that date).

Also, was the tool supposed to automatically only show the MOSTRECENT polygons? It's not for me. It's easily taken care of with a definition query but I wonder if it could be part of the script?

**Comment by allisonmuise** [comment]
That's a good test.

Is CREATEDATE valuable at all? If not, I can easily make it the processing date. I can add it as a new field, too, but I'd rather restrict the amount  of 'junk' fields if they aren't helpful. 

The tools won't filter the output by default, that's up to you to set the definition query. That being said, if the mxd of web map is saved with the definition query/filter in place, only the MOSTRECENT features should be visible whenever it is opened. I can't control this from the script because it is a property of the layer in the mxd or the web map, not of the feature class.

**Comment by SCHNZP** [comment]
I think that the parameters including initial processing date are more useful than CREATEDATE and agree about junk fields so would happily lose the CREATEDATE. Others may have differing opinions?

Cool. Once I had the definition query on it just automatically updated to the MOSTRECENT each time I ran the tool yesterday so that works fine.

**Comment by allisonmuise** [comment]
@SCHNZP : Tool should now add fields to both the service and the input layer for the input parameters - initial date, spatial band, temporal band. I left createdate in as it's the only way to know when it was run

**Comment by SCHNZP** [comment]
Makes sense. Thanks!
