### ISSUE TITLE
Vast Difference between using File Geodatabase vs Personal Geodatabase for Prediction zones

### ISSUE THREAD

**Issue by HPDAnalyst** [Esri/crime-analysis-toolbox#77]
I have tested the newest prediction zones tool for saving the results into File Geodatabase vs Personal Geodatabase. I used the point data that I saved to a file geodatabase in both cases (have not tried using a personal geodatabase point set yet)

I used the same settings for both of them and they both completed the calculation around 16 minutes. The tool display is vastly different in the two.

In the fielgeodatabase, the p value is from 1.26134 to 0.086049, in personal geodatabse though it is from 1.26134 to -3.40282e+38 this results in huge display issues,

also, the prediction zone boundaries is totally different. 

I am attaching the screenshots

![5-4-2016_filegeo_pred_zone_boundary](https://cloud.githubusercontent.com/assets/18291921/15032063/7d2ea48a-1212-11e6-84c3-77a2e3fd51bb.jpg)
![5-4-2016_filegeo_pred_zone_p_values](https://cloud.githubusercontent.com/assets/18291921/15032067/82d497fa-1212-11e6-812f-fb9df1187dba.jpg)
![5-4-2016_personalgeo_pred_zone_boundary](https://cloud.githubusercontent.com/assets/18291921/15032069/88538fe2-1212-11e6-8f49-1ee47f3bde3b.jpg)
![5-4-2016_personalgeo_pred_zone_p_values](https://cloud.githubusercontent.com/assets/18291921/15032071/8c68532e-1212-11e6-9d8b-40cf52366641.jpg)

**Comment by cdelaney585** [comment]
Safa- do both output rasters have the same projection?

**Comment by HPDAnalyst** [comment]
Yes they are all in State plane NV East Fips 2701



Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759

**Comment by a517dogg** [comment]
I got similar results with the prediction zones, where I only have two levels, and lots of squares. I tried saving the raster to a folder instead of a geodatabase and I got this error message:
Executing: CalculatePredictionZones "Crime Categories\Burglary\60 Day\Burglary 60 Days" occur_date YESTERDAY 1000 500 14 7 CUMULATIVE "\\rpdfs.cor.local\mcac$\MCAC Operations\Personal Folders\Martin\beta test ESRI" "\\rpdfs.cor.local\mcac$\MCAC Operations\Personal Folders\Martin\ESRIbetatest.mdb\PredictionZonesRPDBurgs" 4 # NONE # # # #
Start Time: Thu May 05 15:40:08 2016
Running script CalculatePredictionZones...
26 incidents found.
ERROR 010240: Could not save raster dataset to \\rpdfs.cor.local\mcac$\MCAC Operations\Personal Folders\Martin\beta test ESRI\p160505154025 with output format GRID.
Completed script CalculatePredictionZones...
Failed to execute (CalculatePredictionZones).
Failed at Thu May 05 15:44:14 2016 (Elapsed Time: 4 minutes 6 seconds)


Here's a screenshot of one of my bizarre prediction zone rasters:

![image](https://cloud.githubusercontent.com/assets/15637772/15055089/b0069860-12d8-11e6-8173-7be365f7be64.png)

Zooming in on the border between the red and green:

![image](https://cloud.githubusercontent.com/assets/15637772/15055095/bcf39406-12d8-11e6-910c-99d9ab6f19c5.png)

This was looking at RPD burglary data, 60 days (167 incidents in the file). For both prediction zone attempts I used 1000/500 for Spatial range/half distance, and 14/7 for temporal range/halflife.

**Comment by allisonmuise** [comment]
@HPDAnalyst @a517dogg 
Can you tell me more about your overall workflows? Are you testing pgdbs as an alternative test scenario, or are pgdbs the method of data storage used by your organizations? Asked another way - would you be attempting to use a pgdb as part of your actual near-repeat analysis workflow, and if so, why?

I'm actively investigating the differences between raster storage and scratch workspace availability when using personal gdbs, just trying to assess how much of a limitation it would be if this tool can't be made to support pgdbs.

**Comment by HPDAnalyst** [comment]
In our agency, we do not use the file geodatabases to store crime info since it is proprietary and we can’t access them using Crystal Reports. We always use personal geodatabases.

For this Beta testing, I have the crime point data saved both in personal geodatabase as well as file geodatabase.

I have been using the file geodatabase point data so far. But we will not be using that in our production environment due to its proprietary nature and limitation of using Crystal Reports on it.

I will be testing to use the pgdb crime data next to see if the tool will work on that also or error out

The only other option for us will be is we can’t use the pgbd is to use SDE environment since we have to have reports running on this spatial data


Safa


Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759

**Comment by allisonmuise** [comment]
@HPDAnalyst : I can't reproduce this issue when the incidents are stored in an mdb and the output raster is written to either the mdb or a folder.

What is your scratch workspace? (in ArcMap > Geoprocessing menu> Environments > Workspace > Scratch Workspace

I also wonder if you're running up against some space limitations of mdbs....
Is this a dataset you can share with me via email? amuise at esri. com

**Comment by allisonmuise** [comment]
@HPDAnalyst : we've been unable to come up with a repro case for this in-house, and without more information there's not much I can do to track this down. I'm going to push this issue to the next release and keep an eye out for a repro case. If you can share your dataset, computing specs, and ideally your dataset, it will make tracing this for v2 much easier.

**Comment by HPDAnalyst** [comment]
Allison,

how can I send the data only to you?

**Comment by allisonmuise** [comment]
amuise at esri dot com
(without the spaces and with the usual email substitutions, of course)

**Comment by HPDAnalyst** [comment]
Thx


Safa Egilmez
Crime and Intelligence Analyst
Henderson Police Department, NV
(702) 267-4759

**Comment by allisonmuise** [comment]
@HPDAnalyst : I was able to reproduce this once - the first time I ran the tool against your data. I've run it 3x since with the identical settings and every time it's produced the expected results.

Does it work for you when you don't mix mdb and fgdb environments? 
Will your organizations workflows allow you to run these tools in only one of those environments (at least for the first version of the tool)?

**Comment by HPDAnalyst** [comment]
Same problem happening if I use all personal geodatabases (for points as well as storing the prediction zones

![5-11-2016 persgeo_pred-zone-pers_boundary](https://cloud.githubusercontent.com/assets/18291921/15199479/43aac9d8-1793-11e6-8738-25c2f8650184.jpg)

**Comment by HPDAnalyst** [comment]
This problem has been fixed by doing the following:

Change the scratch workspace to a new file geodatabase that is located at the same folder as the near repeat tool,

Have the rasters saved into the folder instead of the geodatabase

used the personal geodatabase and had no problems doing it the above way

Thanks for Chris taking the time to get this fixed
